version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/project/notebooks
      - ./data:/project/data
    command:
      [
        "jupyter-lab",
        "--ip=0.0.0.0",
        "--no-browser",
        "--allow-root"
      ]
